image: mcr.microsoft.com/playwright:v1.45.0-jammy

stages:
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

test_playwright:
  stage: test
  script:
    - npx playwright install --with-deps
    - npx playwright test --project=firefox
  artifacts:
    when: always
    paths:
      - test-results/
    reports:
      junit: test-results/*.xml
